# frozen_string_literal: true

module Dummy
  module TailwindGemSources
    module_function

    GEM_DIRECTORIES = {
      "flat_pack" => ["app/components"],
      "recording_studio" => ["app/views"]
    }.freeze

    ENGINE_CONSTANTS = {
      "flat_pack" => "FlatPack",
      "recording_studio" => "RecordingStudio"
    }.freeze

    def css
      lines = ["/* Generated by rake tailwindcss:inject_gem_sources — do not edit. */"]
      source_directories.each do |directory|
        lines << %(@source "#{directory}";)
      end
      "#{lines.join("\n")}\n"
    end

    def source_directories
      directories = []

      GEM_DIRECTORIES.each do |gem_name, relatives|
        root = gem_root_for(gem_name)
        next if root.nil? || root.empty?

        relatives.each do |relative|
          path = File.join(root, relative)
          directories << path if File.directory?(path)
        end
      end

      directories.concat(bundler_bundle_path_globs)
      directories.uniq
    end

    def gem_root_for(gem_name)
      spec = Gem.loaded_specs[gem_name]
      if spec && spec.full_gem_path && File.directory?(spec.full_gem_path)
        return spec.full_gem_path
      end

      engine_root_for(gem_name)
    end

    def engine_root_for(gem_name)
      constant_name = ENGINE_CONSTANTS[gem_name]
      return unless constant_name
      return unless Object.const_defined?(constant_name)

      mod = Object.const_get(constant_name)
      return unless mod.const_defined?(:Engine)

      root = mod::Engine.root.to_s
      root if File.directory?(root)
    end

    def bundler_bundle_path_globs
      return [] unless defined?(Bundler)

      bundle_path = Bundler.bundle_path.to_s
      return [] if bundle_path.empty?

      [
        File.join(bundle_path, "bundler/gems/flatpack-*/app/components"),
        File.join(bundle_path, "bundler/gems/RecordingStudio-*/app/views"),
        File.join(bundle_path, "bundler/gems/recordingstudio-*/app/views"),
        File.join(bundle_path, "gems/flat_pack-*/app/components"),
        File.join(bundle_path, "gems/recording_studio-*/app/views")
      ]
    end
  end
end
